export declare const TEST_ID_NEWSLETTER_TITLE = "newsletter-title";
export declare const TEST_ID_NEWSLETTER_STANDFIRST = "newsletter-standfirst";
export declare const TEST_ID_NEWSLETTER_SUBCONTAINER = "newsletter-subcontainer";
export declare const TEST_ID_NEWSLETTER_AUTHOR = "newsletter-author";
export declare const TEST_ID_NEWSLETTER_IMAGE = "newsletter-image";
export declare const TEST_ID_NEWSLETTER_SUBSCRIBE_BUTTON = "newsletter-subscribe-button";
export declare const TEST_ID_NEWSLETTER_UNSUBSCRIBE_BUTTON = "newsletter-unsubscribe-button";
export declare const TEST_ID_NEWSLETTER_SIGNED_UP_BUTTON = "newsletter-signed-up-button";
export declare const TEST_ID_NEWSLETTER_PREMIUM_BADGE = "newsletter-premium-badge";
export declare const NEWSLETTER_PREMIUM_BADGE_COPY = "Exclusive for subscribers";
export declare const NEWSLETTER_SIGN_UP_COPY = "Sign up";
export declare const NEWSLETTER_REMOVE_COPY = "Remove";
//# sourceMappingURL=constants.d.ts.map