export declare const SIZE_SMALL = "small";
export declare const SIZE_BASE = "base";
export declare const SIZE_LARGE = "large";
export declare const VARIANT_BASE = "base";
export declare const VARIANT_EXPANDED = "expanded";
export declare const AS_A = "a";
export declare const AS_P = "p";
export declare const AS_SPAN = "span";
export declare const AS_H1 = "h1";
export declare const AS_H2 = "h2";
export declare const AS_H3 = "h3";
export declare const AS_H4 = "h4";
export declare const AS_H5 = "h5";
//# sourceMappingURL=Tag.constants.d.ts.map